# Site settings
title: Vittorio Migliore # site title
description: >- # site description
  Developer
lang: it-IT # default lang
timezone: Europe/Rome # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/vittoriomigliore/vittoriomigliore.github.io # site repo

# Header info
header:
  arg: "vittorioMigliore"
  bio: >-
    I'm a software developer with a passion for crafting elegant solutions to complex problems. <br>
    My expertise covers a range of programming languages and technologies, and I'm committed to writing clean, efficient code.<br>
    In spare time I
  label: Contact me
  avatar: assets/img/avatar.jpg
  avatar_alt: Avatar

# Profile settings
contacts:
  github: vittoriomigliore
  instagram: riot.vito
  twitter: vitto__z
  linkedin: vittorio-migliore
  email: vittorio.migliore@gmail.com

# URL settings
url: "https://vittoriomigliore.github.io" # the base hostname & protocol for your site
baseurl:
permalink: /:title/
google_analytics: 
fb_appid:

# Homepage posts
number_of_posts: 5

pagination:
  enabled: true
  per_page: 3
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

include:
  - _redirects
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules

#Plugins
plugins:
- jekyll-feed
- jekyll-sitemap